---

- name: install common packages
  apt: name={{ item }} state=present
  with_items:
    - traceroute
    - git
    - runit
    - golang-go
    - python-mysqldb
    - nodejs
    - build-essential

- name: create home go directory
  file: path=/home/ubuntu/go state=directory

- name: set GOPATH
  lineinfile: "dest=/home/ubuntu/.bashrc line='export GOPATH=$HOME/go'"

- name: add GOPATH bin to PATH
  lineinfile: "dest=/home/ubuntu/.bashrc line='export PATH=$PATH:$HOME/go/bin'"

- stat: path=/etc/service/runsvdir-ubuntu
  register: service_runsvdir

- include: setup_ubuntu_runit.yml
  when: service_runsvdir.stat.exists == False

- name: copy internal root cert
  template:
    src=../templates/root_cert.j2
    dest=/etc/ssl/certs/internal_root.pem
  become: yes
